apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  namespace: {{ .Release.namespace }}
spec:
  host: {{ template "helm-guestbook.name" . }}.apps-crc.testing
  path: /
  to:
    kind: Service
    name: {{ template "helm-guestbook.fullname" . }}
  port:
    targetPort: 80
