apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "helm-guestbook.fullname"-frontend . }}
  ownerReferences:
  - apiVersion: networking.k8s.io/v1beta1
    controller: true
    kind: Ingress
    name: frontend
    uid: 4e6c59cc-704d-4f44-b390-617d879033b6
spec:
  host: www.example.com
  to:
    kind: Service
    name: frontend
