apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "helm-guestbook.fullname" . }}-frontend
  namespace: guestbook
spec:
  path: /
  to:
    kind: Service
    name: {{ template "helm-guestbook.name" . }}
  port:
    targetPort: 80