apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "helm-guestbook.name" . }}
  namespace: guestbook
spec:
  path: /git
  to:
    kind: Service
    name: {{ template "helm-guestbook.fullname" . }}
  port:
    targetPort: 80